jameshughes89/cs101

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
- README.md
Closes #17 
Copy contributing files over from cs102.
Made changes to reflect cs101
> :new: :memo: Add contributing details

- .github/workflows/sphinx-build.yml
Create an action to build the website with sphinx
This is step 1 before getting the auto deploy action working. 
Copy/pasted from CS102 old action that @twentylemon made 
After this is up and running, I will work on getting it to auto deply to a s3 static website since it's cool.
> :robot: Add action for automatically building course website

- .github/workflows/sphinx-build.yml
Related #22 
Extends action to download and upload the built website to S3
Because it's effin' awesome. Any PR will auto build & deploy to live website. 
action 
More or less copied from cs102's action 
Only that it works on cs102 repo. I assume I set up asw s3 side correctly based on the setup for cs102. 
Time will tell if this works.
> :robot: Setup action for auto build & deploy

- source/conf.py
Closes #14 
Remove mark from copyright
Add 'collaborators' to copyright
Update year on copyright
It's changed significantly.
> :robot: Upate course copyright for 2021

- source/topic1.rst
Fix the use of the image "role". It is currently written as `. image::` instead of `.. image::`.  
As of now, the image is not loaded.
> :bug: :art: Fix the image to actually be shown

- source/topic1.rst
Add a space between the `*` and the text it is to be a bullet point for. 
It was missing and madea a weird link thing instead.
> :bug: Fix typesetting for bullet point for "long version"

- source/topic3.rst
Addresses #12 for topic 3.
Add underscores to python functions.  
1. It's convention
2. Most had them, so I just finished it off.
> :telescope: :lipstick: Topic3 Add missing underscores to function names

- source/lab2.rst
- source/lab3.rst
- source/lab4.rst
Related to #12. 
Add an underscore such that the variables in the input example code is `a_var` and `b_var`. The variable name could still be improved, but for now, whatever --- the example code is supposed to be general anyways.
Just to follow the convention (kinda'). 
Was this change, about changing `aVar` to `a_var` necessary? Probably not.
> :telescope: :lipstick: Labs2, 3, & 4 Add underscore to example variables in input

- source/asn1.rst
- source/asn2.rst
- source/asn3.rst
- source/asn4.rst
Set the assignment due dates to TBD. 
The currently posted due dates were for last year. This will obviously create confusion. 
Top of each assignment file.
> :bomb: Remove old due dates from assignments

- source/topic3.rst
General clean up here and there. Nothing particularly noteworthy other than cutting useless crap. Most exciting thing is putting math-ie math back in. 
Bad 'jokes' are bad
Will need to double check that the math still renders as I think there _may_ be a change needed in the `conf.py` file.
> :mortar_board: Topic3 General cleanup edits

- source/topic5b.rst
Closes #5 
Just clean up with white space for student readability. 
Fix a typo. 
Remove 'screw-em' comment. 
Remove periods from points because I have been excluding them everywhere else for some reason :telescope: 
Just a clean up. For some reason I thought the example was worse than it is.
> :mortar_board: Topic5b Example Cleanup

- source/topic3.rst
Small formatting changes to better match conventions. 
It's better this way.
> :mortar_board::lipstick: Topic3 Cleaning up whitespace in statements/expressions

- source/topic4.rst
Cleaned up some wording in the discussions on (a) nesting, (b) libraries, and (c) NumPy. 
The wording was either wrong, or wrong-ish, or arguable, or nuanced, or needs far more explaining, or bleh
Only the latter portion of the topic. There may be more cleanup needed for the earlier sections. It was just the latter sections that stood out particularly bad to me. 
Most of this, if not all, was vestigial content from back when the content was for UWO's COMP 2120. The focus of 2120 was a little different then a CS 101 course.
> :mortar_board: Topic4 Clean up end sections wording

- README.md
Add a link to csci161 to the readme.
So people can see it if they want. 
Top of readme. 
Literally copy/pasted from CS102 and changed a number.
> :memo: Add link to course to readme

- source/lab3.rst
1. Add a new question to the lab asking them to reverse the order of their `if` statements. 
2. Also emphasize that part 1 should be a function
To maybe break their code so they learn more. Also, many just didn't do the function part.
> :new::mortar_board: Lab3 Add a new question to the end of lab

- source/topic5.rst
Be more specific on the number of lines of code in the last part of the activity. Instead of saying 1 line of code, be clear that it's 1 in the function, and 2 if you count the header. 
It's currently ambiguous, which is no good. 
The 2nd activity.
> :lipstick::mortar_board:  Topic5 Clear up the number of lines of code in activity

- source/topic5.rst
Add whitespace between things that should have it. 
`(a,b)` -> `(a, b)`
`x+y` -> `x + y` 
Convention and looks nicer. 
grep -r ',[^ ]' topic5.rst
> :lipstick::telescope: Topic5 Add whitespace between operators, commas, operands

- assignments_files/asn1.ipynb
Remove excess broken code that were left in cells. Also, for some reason one of the functions they were to write was 3/4ths already done for some reason. 
Broken
I will not merge this until at least Tuesday since the removal of the working part of the one function would be perhaps not very fair to those that have yet to start.
> :bomb: Asn1 Remove code that should not be there

- source/topic7.rst
Change Python -> Colab in the one activity. 
I meant colab. I guess Python isn't _wrong_, but whatever.
> :bug: Topic7 Change python -> colab

- source/asn3.rst
Add a due date for A3. 
I would have preferred Nov 8th in 2021, but that's fall reading week, so, no dice.
> Assignment3 Add due date

- data/airports.csv
- source/topic12.rst
Add the airports csv file and correct the download link. 
It pointed to the old url and was never actually uploaded. 
I put the csv in the data folder
Uploaded. Changed out the link to the old url to a download role thing.
> :bug: Topic12 Fix airport csv download link

- source/asn4.rst
Set the due date and make fun Fun
It needs a due date.
> :mortar_board: Assignment 4 Update due date and title

- source/topic13b.rst
Remove a `-`
It should not have been there
backspace
> :bug: Topic13b Remove extra '-'

- source/lab10.rst
Rename the vars, attributes, and methods to follow conventions better. Also give them the suggestion for the attributes. 
It did not follow conventions before.
> :telescope: Lab10 Follow Conventions Better

- source/topic13.rst
> :bug: Topic13 Remove extra will

- site/index.rst
- Remove the note about both sections.
- Update the summary stuff at the top. 
- Reorg content 
- This was from the time there was an in person and an online section. Not really needed for two in person sections. 
- The intro stuff before was garbage. It's better now. 
- Improve flow
Top of the page.
> 💄 Index More Cleaning

- .github/workflows/sphinx-build.yml
Should have been done in #113 
Make deploy need test 
It was supposed to be there. 
I swear I added it 🤷
> 🤖 Workflow Deploy needs test

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/sphinx-build.yml
- CONTRIBUTING.md
- README.md
- pyproject.toml
- requirements.txt
- setup.cfg
- setup.py
- site/assignments/zombies/asn2.py
- site/conf.py
- src/functions_topic.py
- test/test_functions_topic.py
1. Make use of isort black flake8
2. use setup tools and remove requirements
3. run formatter
4. update readme
5. update workflows
Nice clean code. Also better workflows. 
Basically copied duckbot. 
~Kinda'~
yes
~Im gonna make changes to the workflows in draft version to make sure things work.~
> :robot: :memo::telescope::lipstick Use setuptools and isort flake8 black

- site/topics/values-variables-types/values-variables-types.rst
Clean up the Values topic up to and including "Terminology"
It has not been cleaned in a while
If any y'all think of other relevant "Terminology" for CS 101, let me know.
> 🎓 Values Rework Content Part 1

- site/topics/values-variables-types/values-variables-types.rst
Clean up content up to and including Constants
> 🎓 Values Rework Content Part 3

- site/index.rst
- site/topics/input/input.rst
- site/topics/values-variables-types/values-variables-types.rst
Move Input to its own topic following the variables topic
Feels like the variable topic included too much and it seems like a reasonable thing to stand alone
> :new: 🎓 Move and Enhance Input

- site/topics/values-variables-types/values-variables-types.rst
Put print at the start of the topic title. Also add point about using `print` already. 
It comes before the other bits
> 💄 Values Topic Move Print in Title and Fix Whitespace

- site/topics/functions/functions.rst
Rework function topic more up to and EXCLUDING abstraction.
> :lipstick: Functions Rework Part 2

- site/topics/functions/functions.rst
Rework the abstraction section
Remove unnecessary sections from the latter part of the topic 
Cleaning and, although making libraries and optional params are cool and all, they are not necessary right here.
> 💄 Functions Rework Part 3

- site/topics/functions/functions.rst
Rework the comments part of the function topic.
It could be better
I will go back and re-do the sections I missed. I just have other PRs to merge before I get into that.
> :lipstick: Functions Rework Part 4

- site/topics/functions/functions.rst
As suggested by @twentylemon in #134 
Move the execution flow up in the content. Also fixed a formatting thing with the backticks.  
Makes more sense here since I already moved things around
> 💄 Functions Rework Part 2.5

- site/topics/functions/functions.rst
Noted in #137 
Add more content to the abstraction section. Break the section down into subsections. Add a warning emphasizing that it is non-trivial. 
Let me know if the warning is *tooooo* much.
> 💄 :new: Functions Abstraction Rework

- site/topics/input/input.rst
- site/topics/intro/intro.rst
- site/topics/statements/statements.rst
- site/topics/values-variables-types/values-variables-types.rst
#136 
Fix the spacing so the sub points don't make the parent point bold faced
Because I don't want the parent points to be bold
The first 4 topics
Added a new line between the parent point and the series of children
Leave issue open because it will exist for all the following sections as is. 
I also don't know why it's doing this as it only seems to do this in this theme. Maybe it's intentional? Maybe it's a bug in the theme?
> 💄 Clear Up **Bold Face** Points

- site/topics/functions/functions.rst
Rework the general structure of a function 
Feels like the activities don't REALLY belong in the section, but whatever. They could go anywhere really in the latter half of the topic.
> 💄 Functions Rework Part 5 (general structure)

- site/topics/functions/functions.rst
Indent the link.
It needs to be indented to render properly.
> :bug: Functions Fix YouTube Link

- site/index.rst
- site/topics/testing/testing.rst
From #76 and #85
Create a new empty topic page for testing and type hints.
1. I like the idea of them being more explicitly aware of types earlier since it helps reduce errors
2. Testing is big. I want them to be more used to it. It will help them. I can make use of "tests" in their assignments too. They will be more prepped for the following course. They also said in 2nd semester that they wish they were aware of unit testing earlier. 
Leaving issues open since they should be carried throughout the remainder of the content.
> :new: 🎓 Create New Topic for Testing and Type Hints

- site/topics/functions/functions.rst
Rework the Composition of functions section
It's better this way.
> 💄 Functions Rework Composition Section

- site/topics/functions/functions.rst
Rework scope and import sections
> 💄 Functions Rework Scope and Import Sections

- site/topics/testing/testing.rst
#76 
Introduce testing and motivate it. 
Also add sections for future PRs.
> 🎓 Testing Introduce Topic

- src/functions_topic.py
- test/test_functions_topic.py
Add the code from the topic to a .py file with simple tests. 
Add proper tests for the function topic code
Yes
Format was run
Turns out the `unittest` assertions produce fine messages, so making custom messages was perhaps overkill. 🤷
> 🆕 Functions Topic Code With Tests

- site/topics/testing/testing.rst
#76 
Describe testing with assertions and what happens when they fail. 
To show what happens when it fails, I wrote a broken function.
> 🎓 Testing Testing With Assertions

- src/car_rental_topic.py
- src/functions_topic.py
- test/test_car_rental_topic.py
Put the code from the topic into a script
Yes
1. It may still change once I get to the topic content, but this at least starts it out consistent. 
2. Originally I had it set up so `average_kms_per_day` called `total_kms` so it would be a total of 3 functions deep. I ditched this as (a) I don't think it's necessary to explicitly show, and (b) it may end up being just a little confusing.
> 🎓 Car Rental Topic Code

- site/topics/testing/testing.rst
Simplify wording
Through -> thorough
> :bug:💄 Testing Cleanup

- site/topics/testing/testing.rst
- src/functions_topic.py
Show some tests for `square_of_sum` and discuss them. Also took the opportunity to briefly talk about floating point precision. 
Seeing examples of the tests may be one of the better ways to learn them. 
Eff that
> 🎓 Testing Square Sum Example

- site/topics/testing/testing.rst
Create the type hint sections.
Makes adding them easier later if I do more than one PR. 
On second thought *I probably won't actually have more than one PR 🤷‍♀️
> 🎓 Type Hints Start Sections

- site/topics/testing/testing.rst
- src/functions_topic.py
- Include another example of testing (`celsius_to_fahrenheit`)
- Mention `unittest`, but that's it. 
The more the merrier.
> 🎓 Testing C to F Tests and Automation

- site/topics/testing/testing.rst
Motivate type hints. 
Show them how to do type hints
I think the motivation is good, but the type hints don't actually solve the problem in the original motivation example since they're only for the programmer. 
The inclusion of the subsection "What You Don't Get" is to cover this.
> 🎓 Type Hints Part 1

- .gitignore
Remove `/site` from gitignore. 
So I can add stuff.
I was wondering why every new file I made was ignored.
> 💣:memo: Remove Site From gitignore

- .github/workflows/sphinx-build.yml
As discussed in #166 
Rename `site` to `builtsite`.
Eliminate potential confusion. 
No, but also kinda' yes
> :robot: Deploy action site -> builtsite

- site/topics/booleans/booleans.rst
Rework the intro to booleans and talk about truth tables.
Gotta' start somewhere. 
Start at the start and go up to the video html link.
> 🎓 Booleans Intro and Truth Table

- site/topics/car-rental/car-rental.rst
Rework the introduction to the topic to include the problem solving strategy from the boolean topic. 
It feels like it belongs better under this topic, so this move (and rework) was done. Also, the compounding interest example isn't really a great example of building bigger functions since it legit can be one line long.
> 🎓 Car Rental Rework Intro

- site/topics/booleans/booleans.rst
- site/topics/car-rental/car-rental.rst
- site/topics/testing/testing.rst
- site/topics/values-variables-types/values-variables-types.rst
Correct spelling throughout the topics so far. 
Up to what was already updated in the content. 
Got the spellchecker working again. Turns out I had PyCharm in "Reader Mode" which I guess means it will not worry about spelling. 🤷
> 🐛:lipstick: Correct Spelling

- site/topics/car-rental/car-rental.rst
Add a `*` and hit tab. 
Consistency
> 💄 Car Rental First Sentence As Point

- site/topics/car-rental/car-rental.rst
Add dots after the `#` used for an auto-enumerdated list. 
I guess they're needed for them to render correctly.
> :bug: Car Rental Topic Add Dots to Enumerated

- README.md
python3.8 -> python3.10 in readme on setup
it actually requires 3.10 
ooops.
> :memo: :bug: Readme 3.8 -> 3.10

- README.md
Add unittest to the readme
Eventually I will go and add details on who/what/when/why/where/how to Format and Unit Test in the readme.
> 📝 Readme Unittest

- site/topics/if-else/if-else.rst
- src/if_else_topic.py
- test/test_if_else_topic.py
Show that `else` is a thing. 
It's cool. 
Yes.
The *note* originally only was going to include version 2, but I opted to include version 3 as a way to demonstrate how the same functionality can be achieved with different implementations. It is perhaps a little contrived, but usually at this stage of the course they don't really have an appreciation of how there are literally an infinite ways to do anything. I figure, showing a few alternatives (despite how small of an example this is) may be helpful.
> 🎓 If Else Topic Introduce `else`

- site/topics/if-else/if-else.rst
- src/if_else_topic.py
- test/test_if_else_topic.py
else ifs are pretty great. 
Yes.
> 🎓 If Else Topic `elif``

- site/topics/if-else/if-else.rst
- src/if_else_topic.py
- test/test_if_else_topic.py
Show an example of an `if` with more complex compound expressions. 
Yersh 
Next topic will cover `else`
> :mortar_board: If Else Topic Compounding Expressions

- .gitattributes
As pointed out by @twentylemon in #184 
Add git attributes to set EOL for text files. 
Consistency 
I renormalized based on .gitattributes` before merging #184 to ensure it did exactly the same thing. It did.
> :memo: Add Git Attributes

- setup.py
Add the jupyter option to black setup install. 
It will also run format on the `.ipynb` files, which is cool. 
Yep, through running and doing format and it worked.
> :memo: Add jupyter option for black

- site/topics/car-rental/car-rental.rst
Start reworking the "putting it together" section. 
Just a general cleanup. It's only the first 2 functions being added so far. 
Yeeeep
> 🎓 Car Rental Topic Putting It Together

- site/topics/loops/loops.rst
Rework the intro parts to the loop topic. 
Intro and reusing variables.
> 🎓 Loops Topic Rework Introduction Bits

- site/topics/strings/strings.rst
Rework the introduction to strings. The focus is indexing.
> 🎓 Strings Topic Rework Intro Part

- site/topics/lists/lists.rst
Remove the empty activity that was breaking the other activity. 
I broke it resolving merge conflicts
> :bug: Lists Topic Remove Activity Breaking Page 🔬 

- site/topics/car-rental/car-rental.rst
Write the section for `num_kms_above_average`
Ignore the name of the branch. It's lying.
> 🎓 Car Topic `num_kms_above_average`

- site/topics/car-rental/car-rental.rst
- src/car_rental_topic.py
Based on the suggestion from @twentylemon in #197 
Reorder the way the ideas are presented such that we start at the _end_, work our way down, solve sub problems, and then work our way back to the end. 
Also finished off the topic. 
1. @jdelamer, you will need to update the colab link. 
2. I opted not to bother with the `assert`s for the input part and just did prints. There is nothing stopping the use of `assert` for the types.
> 🎓 Car Rental Topic Reorder and Finish

- site/topics/if-else/if-else.rst
Change c -> C in Chapter. 
Consistency with other topics. 
I assumed I had this issue in more places, but I guess just one place.
> 💄 chapter -> Chapter

- site/topics/loops/loops.rst
Remove the old part of an activity. 
It was supposed to get removed. I think it may have been a merge conflict but I am too lazy to confirm.
> :bug: Loops Topic Remove Old Activity Part

- site/topics/loops/loops.rst
- src/loops_topic.py
- test/test_loops_topic.py
Introduce while loops.
Yes
The mystery function is named properly in src
> 🎓 Loops Topic While Loops

- site/topics/strings/strings.rst
Say that strings are immutable 
Because they are
> 🎓 String Topic Mutability

- site/topics/strings/strings.rst
Change activity to code block. 
Should've been one in the first place. I lazily copy/pasted without paying attention.
> 🐛 Strings Topic Change Activity to Code Block

- site/topics/loops/loops.rst
- src/loops_topic.py
- test/test_loops_topic.py
Add activities for summing integers. Also remove section on encapsulation since these ideas are covered more-or-less in the function topic. 
There is no expectation that their `int_sum_print` formats nicely.
> 🎓 Loops Topic `int_sum` and `int_sum_print`

- site/topics/strings/strings.rst
- src/strings_topic.py
- test/test_strings_topic.py
Linear search activity and discussion 
It's their first, like, standard common algo. 
There is also a touch on the length of the sequence to lead into thinking about computational complexity. 
The use of  checking equality with booleans (`assert False == character_is_in("a", "")`) was intentional as it will be more clear to the new programmers.
> 🎓 Strings Topic Linear Search

- site/topics/strings/strings.rst
Add backticks to fix the typesetting of the math bits
> 🐛 String Topic fix math typesetting 🔬 

- src/car_rental_topic.py
Fix format of src for topic. 
Accidentally changed something somewhere.
> 💄 Car Topic src fix format 🔬 

- site/labs/hello-world/hello-world.rst
> 🎓 Lab1 general rework

- site/topics/strings/strings.rst
Show them that f-Strings exist and that they're great.
> 🎓 Strings Topic f-Strings

- site/topics/strings/strings.rst
- Format the trivia a little nicer by indenting the code.
- Add an example for the quotes
- Change "buttons" to "keys"
> 💄  Strings Topic clean up trivia a tad

- site/topics/lists/lists.rst
Discuss `+` and `*` and have them play with the methods.
> 🎓 Lists Topic operators and methods

- site/topics/strings/strings.rst
Indent the sequences 
It will look nicer this way.
> 💄 Strings Topic indent math sequences 🔬 

- site/topics/loops/loops.rst
Add a period and say "... to verify correctness." to the last activity. 
Missing period was inconsistent. Sentence felt too boring without the other bit.
> 🐛 Loops Topic clean last activity 🔬 

- site/labs/functions/functions.rst
Clean up lab 2. 
Annoyingly all the relevant exercises from the online "book" are about turtle graphics.
> 🎓 Lab2 rework content

- .github/PULL_REQUEST_TEMPLATE.md
Update the issue template to get rid of the new line. 
The extra newline after the heading and the text is annoying. CS102 already has it without the newline.
> 📝 Update PR template 🔬 

- site/topics/lists/lists.rst
1. Remove range section
2. Clean mutability section
`range` should be shown somewhere still in the context of a `for` loop.
(edit) I will hit it later in THIS topic since there is already a sec for it.
> 🎓 Lists Topic mutability

- site/labs/loops/loops.rst
> 🎓 Lab5 general cleanup

- site/labs/conditionals/conditionals.rst
> 🎓 Lab3 clean

- site/labs/car-rental/car-rental.rst
Clean up the car rental lab 
Turns out this one should be lab 4 and loops are lab 5. Long story short, I mislabeled the loop lab in a PR.
> 🎓 Car Lab general cleanup

- site/labs/linear-search/linear-search.rst
> 🎓 Lab6 clean

- site/topics/lists/lists.rst
Looping on lists
Mostly examples
1. Not sure if this is the best place to introduce `range`
2. May want to move the subsequent sections to the topic *after* references
* This topic is already getting long
* It makes sense to talk about aliases after references
3. Need to go and check for indentation consistency throughout the lecture content since colab likes 2 spaces. This is a setting on colab that can be changed, but I only did it now and then realized the issue.
> 🎓 Lists Topic loops on lists

- site/index.rst
- site/labs/1d-lists/1d-lists.rst
As discussed in #130 
Include a new lab covering lists 
1. Students in CS102 said they would have liked to have more list content in CS101 (#130)
2. Before, the first list lab jumped straight to 2D lists from strings
3. Before, labs always seemed to get a little ahead of lecture content, so this can slow them down in terms of content. 
The question on `replace_all`  was originally going to be in two parts --- one with side effects and one without. I opted not to do this as I am not sure if we will have sufficiently covered references, aliases, and side effects yet.
> :new: 🎓 1D List Lab

- site/labs/1d-lists/1d-lists.rst
- site/labs/2d-lists/2d-lists.rst
Clean up the lab on 2D lists. 
Consistency
> 🎓 2D List Lab clean up the lab on 2D lists

- site/topics/lists/alias-trivia.rst
Pass by reference, side effects, and pure functions
> 🎓 Alias Topic pure and not pure functions

- site/topics/lists/alias-trivia.rst
- src/lists_topic.py
- test/test_lists_topic.py
Show some basic cool stuff about lists
Presents some basic and common-ish uses
Yeah. 
Put the one test from the topic in the lists tests, but could still move it to its own test script.
> 🎓 Lists Trivia

- site/assignments/tic-tac-toe/tic-tac-toe.rst
- site/index.rst
- site/labs/debug/debug.rst
- site/labs/hello-world/hello-world.rst
- site/labs/more-objects/more-objects.rst
- site/labs/recursion/recursion.rst
- site/topics/if-else/if-else.rst
- site/topics/input/input.rst
- site/topics/lists/alias-trivia.rst
- site/topics/lists/lists.rst
- site/topics/sorting/sorting.rst
- site/topics/strings/strings.rst
Fix a collection of sphinx warnings. 
Throughout 
Some fixes were in parts that were not cleaned up yet and they would have been addressed later anyways. I opted to just do it here to eliminate the warnings.
> :lipstick: :bug: :telescope: Fixing sphinx warnings

- site/topics/tuples-dictionaries-sets/tuples-dictionaries-sets.rst
Explain dictionaries, but at a pretty high level. 
They're awesome, but the nitty gritty details are outside the scope of the course. 
Further, it is expected that, although they will [likely] use dictionaries in A4, they will not really remember them or make much use of them. The main purpose of showing them dictionaries is because they will start making more use of them in the following course.
> 🎓 Dictionaries 

- site/topics/tuples-dictionaries-sets/tuples-dictionaries-sets.rst
Bug created in #254 
Unindent the start of the codeblock. 
It did not render correctly given the incorrect syntax n' all
> :bug: Dictionary fix code block 🔬 

- site/topics/debug/debug.rst
Add a few points setting the perspective. 
It's not uncommon for them to get a little lost in the weeds.
> :new: Debugging prepare mentality 🔬 

- site/topics/debug/debug.rst
Hit logic errors and start with `print` for debugging
prints are simple and effective, especially at this stage of learning. It also has a nice benefit of having them really think about the values of variables themselves instead of just throwing stuff at the computer.
> 🎓 Debugging logic bugs and `print`

- site/topics/debug/debug.rst
Show some of the errors they are likely to see error messages for. Only the syntax and type errors are discussed in their own sections, but time will be taken during lecture to hit each of those in the point form list. 
At this stage they have likely seen many of these errors, and may already be familiar with addressing them. Either way, it will help make sure people are on the same page-ish. 
I do like my segue in Type Errors from error messages to no error message, and how the following section hits logic errors. 
This topic is going to be far far far from thorough. It's purpose is just to get them thinking about these things explicitly and hopefully they are equipped enough to learn more as they go.
> 🎓 Debugging syntax errors and type errors

- site/topics/debug/debug.rst
Explain "delta debugging" (but not really) and rubber duck debugging
Next year the students will all be getting a StFX Branded Rubber Duck, so that's awesome.
> :mortar_board: Debugging delta debugging and rubber duck debugging

- site/topics/fileIO/fileIO.rst
> :mortar_board: FileIO reading and writing to text files

- site/topics/fileIO/fileIO.rst
Reading and writing CSV files
They're greeeeat
> 🎓 File io CSV files

- site/topics/fileIO/fileIO.rst
Change test -> text
It should have been text --- they're teXt files.
> 🐛 FileIO test -> text 🔬 

- site/topics/exceptions/exceptions.rst
Clean up the intro bit to the exceptions topic
> 🎓 Exceptions intro rework

- site/topics/exceptions/exceptions.rst
- site/topics/objects/objects.rst
Clean the next class section and move the one reading to the subsequent topic
Moving the reading makes sense since they were both on objects, and the discussion on topics in the course are over two topics. Thus, this spread out the reading better.
> 🎓 Exceptions and Objects next class 🔬 

- site/index.rst
- site/labs/objects/objects.rst
- site/topics/objects/collections.rst
Move object content into single folder. Update references. 
No content has been changed 🔴. 
It's nicer this way.
> 🎓 Objects move content around

- site/topics/exceptions/exceptions.rst
Example of the program halting once the exception is seen
> 🎓 Exceptions example exit()

- site/topics/exceptions/exceptions.rst
An example where the exception is simply ignored.
> 🎓 Exceptions catching ignore example

- src/point.py
- test/test_point.py
A Point class for a topic covering more on objects. 
The 2nd objects topic will focus more on methods and the point class has more methods that seem a little "fancier" than the circle (parameters, returning something of the same type).
:+1:, though, I am longing for parameterized tests. 
I'm really liking the idea of introducing `unittest` after this topic such that the topics go:
- Objects 1 --- constructor and attributes and methods
- Objects 2 --- More on methods
- Unit testing with `unittest` 
- Objects 3 --- Collection (list of some objects) 
Motivation for the `unittest` topic is:
1. Asserts are starting to be limiting as the tests are requiring a little more setup
2. Asserts get jumbled together and not trivial to understand what the test is just by looking at it 
3. If the first …
> 🎓 Point class

- site/index.rst
- site/topics/testing/unittest.rst
Create an empty rst file that will have the unittest content. 
**Other than the reading, no content is added here**
This helps me for later when I made the content.
> 🆕 Unittest topic create blank topic file 🔬 

- src/Course.py
- src/course.py
- test/test_course.py
A `Course` class for keeping track of students. 
They get to make a collection. 
:+1:, and yeah --- will defo have to have covered `unittest` before this one.
> 🎓 Course class

- site/labs/objects/objects.rst
Redo the objects/class lab. 
Student feedback from the subsequent course (CS102) was that they wanted more practice with objects/classes in CS101. This lab is a more basic version of what it was, and there will be another objects lab following this one that will be a little more fancy. The following lab will be a collection of some sort I think.
> 🎓 Lab objects redo lab

- site/topics/objects/introduction.rst
- src/circle.py
Add details on what we want the circle to be and update docstring for class. 
I think it will help with the flow of the topic.
> :new: Objects explain what the circle will do earlier

- site/labs/objects/objects.rst
Fix typesetting of the one question in the lab. 
It was boldfaced when it should not have been 
Added a new line between the two points. This sphinx theme makes the point bold if you do not add the space.
> :bug: Objects Lab fix typesetting 🔬 

- site/topics/testing/unittest.rst
Introduce the `unittest` topic and layout some sections.
Gotta' start somewhere, and I like to have an idea of sections before I start writing them. 
The number of sections and the section names may change --- I just need a starting point.
> 🎓 Unittest Topic introduction

- src/student.py
Remove extra space between words. 
It doesn't belong.
> 💄 Student class remove extra space 🔬 🔬 🔬 🔬 

- site/topics/testing/unittest.rst
Add a link to the GitHub repo so they can check out the unittests written for the course.
> :new: Unittest Topic next class link to repo 🔬 

- site/index.rst
Add captions/titles to the parts of the table of contents side bar
This should make it SO much easier to view
> 🆕 Add captions to table of contents side bar

- site/topics/objects/methods.rst
Introduce what the topic will be about and add sections/subsections/subsubsections. 
The Testing subsection under the Sphere section will basically be "Eff using the assert tests.... we need unittest", which will be a nice segue for the subsequent topic.
> 🎓 Objects Methods Topic introduce topic and create sections

- site/topics/testing/unittest.rst
#218 explains how the test class names will be changed to match what is actually presented in this topic. 
Show how to start writing the test class
You may notice that the actual test is called `TestPoint3D`, but in the code snippet shown, it is `Point3D` test. The actual test class names in the project will be changed to match what is presented in the topic.
> 🎓 Unittest Topic set up unittest

- site/topics/objects/data-structures.rst
Introduce and motivate the learning of data structures.
> 🎓 Data Structures Topic introduction

- site/topics/objects/introduction.rst
Add a `-` 
sphinx was mad that the underline was too short.
> :bug: Objects Intro Topic fix title underline 🔬 

- site/topics/objects/methods.rst
Related to #316
Discuss the `Sphere` class' methods, but not the magic methods yet. 
Based on the original version of the PR from #316.
> 🎓 Objects Methods Topic first set of methods for `Sphere`

- site/topics/objects/methods.rst
- src/sphere_original.py
Related to #315
Introduce the `Sphere` class and show the constructor. 
I was trying to have a difference between using sphere to refer to the general idea of a sphere and `Sphere` to refer to our specific class, but I found it too tedious so whatevz.
> 🎓 Objects Methods Topic sphere class 

- site/topics/objects/methods.rst
Related to #317 
Introduce the idea of magic methods and show `__eq__`
> 🎓 Objects Methods Topic magic methods and eq

- site/topics/testing/unittest.rst
Show how to run `unittest` on Colab. Also show some sample output of passed and failed tests.
> 🎓 Unittest Topic running tests on colab

- site/topics/objects/interacting-objects.rst
- site/topics/objects/methods.rst
Show the relevant magic methods.
~This PR was going to include the `__repr__` details too, but it started to get too long. ~
> 🎓 Objects Interacting Topic magic methods

- site/topics/testing/unittest.rst
Update the intro bits to say we are testing `Sphere`, not `Point3D`
> 🐛 Unittest topic `Point3d` -> `Sphere` 🔬 

- site/topics/objects/interacting-objects.rst
- site/topics/objects/methods.rst
Show the basic `assert` tests for the `Point3D` class. Also emphasize that the `assert` tests are starting to show their limitations.
> 🎓 Objects Interacting Topic testing `Point3D` class

- site/topics/testing/unittest.rst
- test/test_sphere.py
- test/test_sphere_original.py
Show the basic setup/template for tests. 
Fortunately it doesn't seem to difficult to get into as they will have been writing their `assert` tests for a while now.
> 🎓 Unittest Topic writing tests

- site/topics/objects/interacting-objects.rst
- site/topics/objects/methods.rst
- src/point3d.py
- test/test_point3d.py
Discuss the methods within the `Point3D` class. 
Despite being within the "Methods" subsection, the "Magic Methods" subsubsection is skipped here as that would make this PR too big.
> 🎓 Objects Interacting Topic  `Point3D` class' methods 

- site/topics/objects/interacting-objects.rst
The testing subsection points out how limited our original style of tests are. The section also motivates the use of a better framework for testing.
> 🎓 Objects Interacting Topic explain how simple `assert` tests are lacking

- site/topics/objects/data-structures.rst
- src/course.py
Discuss the `Course` object and the various methods. 
1. I am pretty sure I have shown them the loop and appending to a string at some point before this 
2. I was going to have the *For Next Class* be downloads to the test files, but since they have been using Colab, the .py files may throw them. Linking right to github at least has the code nice and viewable.
> 🎓 Data Structures Topic `Course` section

- src/sorting_topic.py
- test/test_sorting_topic.py
Add `insertion_sort`, `bubble_sort`, and `bubble_sort_improved` (bubble sort, but uses a flag to check if any swaps took place) to the repo. 
They will be discussed (though, the improved bubble will probably just be a footnote in the topic). 
:+1:
> 🎓 Sorting Topic add insertion, bubble, and another bubble

- site/topics/sorting/sorting.rst
Remove the old content on:
1. BOGO sort
2. Not really needed motivation
Also did some other small cleanup, like section names. 
The removed stuff was not needed. Motivation for sorting is hopefully not really needed. BOGO sort is fun I guess, but really not necessary. 
If anyone insists on BOGO sort staying, I will keep it.
> 🎓 💣 Sorting Topic remove old content

- site/topics/sorting/sorting.rst
1. Move where the text explaining each step of Bubble Sort is
2. Move link to visualization to "For Next Class" section
1. Looks better this way --- before it looked quite clunky 
2. The link felt lonely in it's own section
> 💄 Sorting Topic clean up 🔬 

- .github/workflows/sphinx-build.yml
- README.md
Include SETUPTOOLS_ENABLE_FEATURES="legacy-editable" for the repo. 
There was an update, and things broke I guess. 
Mostly copy/paste from duckbot. 
I tried testing locally, but I could not re-create the issue locally for some reason. PR will do the test. 
🤞
> 🤖 Fix setuptools editable legacy issue

- site/index.rst
- site/outline/outline.rst
Update the course syllabus/outline for Fall 2022. 
- Dates/rooms/times
- Office hours formats
- Add testing to topics
- Update lab details
- General formatting 
- Remove old info
Semester is about to start 😬 
@jdelamer, you should have a looksie to make sure everything is correct on your end.
> :new:💄 Syllabus Update for Fall 2022

- site/outline/outline.rst
Adding a short sentence to what was added in #372 
Emphasize that there are no make-up tests. 
More clarity. This makes it quite explicitly clear. 
By saying there are no make-up tests.
> 🎓 Syllabus --- Emphasize no make-up midterm

- site/outline/outline.rst
As a consequence of #370 
Reduce the number of labs mentioned from 12 -> 11. Also a fix to the sentence. 
There is now only 11 labs, which is for the best as there is no way we will have all 12 labs due to university closures on Fridays and Mondays.
> :bug: Syllabus --- Reduce Lab Number

- site/index.rst
Remove the links to the assignments from the main index page. 
The assignment descriptions are not ready yet for this year. 
Commented out the links for now.
> :bomb: Index --- Remove links to assignments 

- site/outline/outline.rst
Fix the content such that the typesetting works properly
Points didn't point
> :bug: :lipstick: Syllabus --- Fix point form points

- site/outline/outline.rst
Remove an extra comma that should not have been there. 
It should not be there.
> :bug: Syllabus --- Remove extra comma

- site/topics/intro/intro.rst
Actually link to colab on the page. 
Will make it easier to get there.
> :new: Intro --- Link to Colab website

- site/topics/values-variables-types/values-variables-types.rst
Add SSD to the part where HDDs are mentioned
They are a thing that are common now
> :new: Values --- Add SSD

- site/topics/values-variables-types/values-variables-types.rst
Fix the typesetting for a sentence discussing print with codelike text. Also re-stated print being a function too, because why not. 
It was busted.
> :bug: Values --- Fix typesetting on print sentence

- site/assignments/starbucks/starbucks.rst
- Write/rework the details on uploading the relevant files to Google Colab. 
- Remove the few details on working on your own computer. 
- They will need help with this
- Removed the details on working on own comp since (a) I really do not recommend it, (b) if they do end up opting for doing it locally, chances are they know what they're doing in terms of interacting with an IDE, and (c) I really do not want that kind of support to be my problem at this stage of the game.
> :mortar_board: Assignment 1 --- Uploading files section

- site/assignments/starbucks/starbucks.rst
Update the details on the part of the assignment telling them to look at the provided loading function. 
It's a good exercise, even if it has some advanced ideas. 
I removed the content from below, but still left the details on how one does not need to use the degree -> decimal function as I will mention that in the degree -> decimal section.
> :mortar_board: Assignment 1 --- Investigating load function section

- site/assignments/starbucks/starbucks.rst
Explain what is needed for the degrees -> decimal function.
> :mortar_board: Assignment 1 --- Degrees to decimal description 

- site/topics/intro/intro.rst
Change an `h` to an `H` 
Consistency --- all other section titles in the topic have all uppercase
It annoys me.
> :lipstick: Intro --- Title Full Uppercase

- site/topics/values-variables-types/values-variables-types.rst
Similar to #377 
Change a `d` to a `D`
Consistency. All other sections have all uppercase.
> :lipstick: :telescope: Values --- Uppercase Section Titles

- site/index.rst
Update the link to the learning centre details and add words describing it briefly. 
They changed it.
> :mortar_board: Index --- Learning Centre Link

- site/assignments/starbucks/starbucks.rst
- Add the not-so-helpful hints
- Mention some marking details
- Explain the submission
Copy/pasted form cs102
FAQ was left out of this PR intentionally.
> :mortar_board: Assignment 1 --- Hints, Marking, and Submission

- site/topics/functions/functions.rst
Specify that the sum is calculated and then stored in variable. 
Sure, it may be obvious, but since it's so early in the semester and it is explicitly mentioned in the line about squaring, I figure it could be made a tad clearer.
> :mortar_board: :telescope:  Functions --- Calculate sum and then store  :microscope: 

- site/topics/functions/functions.rst
Missed in #134
Show the errors that pop up when providing too few or too many parameters to a function. 
Seems like I just forgot to fill in this detail when the content was re-done.
> :mortar_board: Functions --- Show errors from too few/many parameters

- site/topics/functions/functions.rst
Change "live" to "life"
> The same is true for your every day live
Because this doesn't make a lot of sense.
> :bug: Functions --- Change live to life :microscope: 

- site/assignments/starbucks/starbucks.rst
- site/index.rst
- site/topics/functions/functions.rst
Fix the sentence that says "like 8" to be "line 8".
Typo.
> :bug: Functions Topic --- Change "like" -> "line" :microscope: 

- site/topics/testing/testing.rst
- Fix the typesetting for some code like text
- Add a missing type to the docstring
> :bug: Testing & Type Hint Topic --- Fix typesetting and add missing type :microscope: 

- site/assignments/starbucks/starbucks.rst
- Clean up head of page
- Add download links to top 
It's nicer, and why not have direct links to the download at the top of the page?
> :lipstick: Assignment 1 --- Clean up head of assignment page

- site/topics/functions/functions.rst
Change the math in an example to be correct. 
The square of the sum of 3 & 3 is not 81 --- it's 36. 
I did the math correctly this time. 
I used a calc to make sure I was not losing it. 
Kinda' urgent.
> :bug: Functions Topic --- Fix bad math :microscope: 

- site/assignments/starbucks/starbucks.rst
As noted by ~@jameshughes89~ @twentylemon in #407 
Change methods -> functions
They're not methods --- they're functions. 
lazy copy/paste from cs102 cause it.
> :telescope: :bug: Assignment 1 --- Methods -> Functions

- site/assignments/starbucks/starbucks.rst
Add a due date of Oct 10 for assignment 1. 
They keep asking about it, and I guess we need one :shrug: 
Oct 10 because:
- Conditionals will be hit this week
- They need conditionals for assignment 
- I like 2 weeks for them
- I like them due on Monday
It's defo a little later this year, but it's just because of how things were re-arranged. I anticipate that subsequent assignments will not have the bottlenecks like asn1 had (needing to get to conditionals).
> :mortar_board: Assignment 1 --- Add due date

- site/assignments/zombies/zombies.rst
Introduce the task they are to do for Asn2. Show the provided file. Also change the warning to a note since it's more of a note than a warning. 
The actual provided files are not changed yet; they are the old versions. New versions will be in another PR.
> :mortar_board: Assignment 2 --- Present task and discuss provided file

- site/assignments/zombies/zombies.rst
Add details on the part about uploading and reading existing code.
- For upload, how is copy/paste from asn1, but no images included. Just said to reference asn1 if you forget. 
- For read, it's basically the same with a note on the eyeball tests.
> :mortar_board: Assignment 2 --- Upload and Read parts

- site/assignments/starbucks/starbucks.rst
Change due date to be 1 day later. 
The Monday is a holiday, and j don't wanna' be like that.
> :new: Assignment 1 --- Change due date

- site/assignments/zombies/zombies.rst
Present Part 2 & 3 of the assignment --- `is_infected` and `get_neighbours` respectively. 
I need to go back and add the details on the city "data structure" to Part 0.
> :mortar_board: Assignment 2 --- Discuss `is_infected` and `get_neighbours`

- site/assignments/zombies/zombies.rst
Explain the `cure` and `infect` functions. 
Emphasis is added on making it a COPY of the city.
> :mortar_board: Assignment 2 --- `cure` and `infect`

- site/assignments/zombies/zombies.rst
Undo the merge of #426. I was rushing because I had to pee and I hit the wrong button.
> :arrow_backward: Undo early commit

- site/assignments/zombies/zombies.rst
Explain the functions for counting the number of cities infected within the world and checking if the whole world is completely infected. 
Emphasis in the form of _italics_ was added to the description as a hint. This may not be necessary, but since they will have only just learned about linear searches, it's probably good to have the poke to the right direction.
> :mortar_board: Assignment 2 --- `number_of_cities_infected` & `is_world_completely_infected`

- site/assignments/zombies/zombies.rst
Explain the full simulation function
similar to the sim step, this one is a toughie so I do a little hand-holding with the pseudocode.
> :mortar_board: Assignment 2 --- Full simulation function

- site/assignments/zombies/zombies.rst
Explain how to run the code to do a quick analysis of the results of their simulations. 
I think it's fun. 
I am worried about the complexity of generating a distro of results, so I am considering giving them the code the running the simulation 100x. What y'all think?
> :mortar_board: Assignment 2 --- Using the code for analysis

- site/labs/loops/loops.rst
> :bug: Lab 5 --- Add missing `"`

- site/topics/strings/strings.rst
Fix typesetting around a _code like_ text.
I added a space.
> :bug: Strings Topic --- Fix typesetting

- site/topics/loops/loops.rst
Replaced "s" with "w" on line 50.
This is cool.
> :bug: Loops topic --- Typo sill -> will 

- site/topics/lists/lists.rst
> :bug: Lists topic --- Typo `od` -> `of`

- site/topics/strings/strings.rst
Change:
"The method `a_string.upper()` is about with the data within the object"
To:
"The method `a_string.upper()` is about the data within the object"
The with should not have been there.
> :bug: Strings Topic --- Fix wording

- site/topics/car-rental/car-rental.rst
- src/car_rental_topic.py
Change `@` -> `:` in the docstrings for the functions. 
Was using wrong convention
I did, for fun.
> :bug: :telescope: Car Rental Topic --- Change the `@` to `:` in docstrings

- site/assignments/tic-tac-toe/tic-tac-toe.rst
Set the due date for the assignment. 
It'll be 3 weeks after assignment 2. Normally I would aim for 2 weeks but the due date of the 14th would be right after reading week and there will be no office hours during reading week. 
This does mean that Assignment 4 will have at most 2 weeks to be due on the 5th, which is the last Monday of the semester.
> :mortar_board: Tic-Tac-Toe Assignment --- Set due date

- site/topics/exceptions/exceptions.rst
Clean up last section of topic
- There was bad typesetting 
- Added "ultimately" to make the point flow from the previous better
- Time should not have a capital, and i made it italics
> :lipstick: Exceptions Topic --- Cleanup last section :microscope: 

- site/labs/lists/1d-lists.rst
Remove the assert test for Q4. 
It does not make sense in that context.
> :bomb: Lists Lab --- Remove request for assert test

- site/assignments/tic-tac-toe/tic-tac-toe.rst
Add section on uploading notebook to Colab. 
Copy & Pate from assignment 2.
Section title changed too. Originally I said to make a new notebook, but this was wrong.
> :mortar_board: Tic-Tac-Toe --- Uploading notebook to Colab

- site/assignments/tic-tac-toe/tic-tac-toe.rst
Describe the `setup_game` function. Also explain how the board is represented and warn about aliases as that is the classic error of the assignment.
> :mortar_board: Tic-Tac-Toe Assignment --- `setup_game` function

- site/assignments/tic-tac-toe/tic-tac-toe.rst
Adding to #462 
Mention that 0,0 is top left.
Why not just be clearer?
> :mortar_board: Tic-Tac-Toe Assignment --- Setup game note 0,0 is top left :microscope: 

- site/assignments/faq.rst
- site/assignments/starbucks/starbucks.rst
- site/assignments/zombies/zombies.rst
1. Consolidate FAQ points into separate page
2. Keep assignment specific FAQ in assignments
3. Make less sarcastic 
Kids these days
~I'll check artifact~
:+1:
> :lipstick: Assignment FAQ --- Consolidate FAQ

- site/assignments/tic-tac-toe/tic-tac-toe.rst
- Describe what makes a move valid
- Discuss a function to determine if a move is valid --- `is_move_valid`
- Provide examples of using the function
- Warn about indexing order
> :mortar_board: Tic-Tac-Toe Assignment --- `is_move_valid` function description

- site/assignments/tic-tac-toe/tic-tac-toe.rst
Tell them to read the assignment. 
Many usually don't. 
Forgot this one.
> :mortar_board: Tic-Tac-Toe Assignment --- Read the assignment :microscope: 

- site/assignments/tic-tac-toe/tic-tac-toe.rst
Kinda depends on #467 
Update the assignment FAQ to follow what _will_ be happening in #467
> :telescope: Tic-Tac-Toe Assignment --- Update FAQ

- site/topics/fileIO/fileIO.rst
Added `close` to the file in the example. 
Although fine that it's not there, to be consistent with the rest of the content, closing it is good. 
J. Hughes edited the PR to help with format of PR.
> :lipstick: FileIO Topic --- Add `close` to example. 

- site/topics/objects/introduction.rst
Capitalize a letter t
Consistency 
@RaZkI-37, I fixed the PR title and description. Try to do it like _this_ from now on.
> :lipstick: Objects I Topic --- Change t -> T

- site/assignments/tic-tac-toe/tic-tac-toe.rst
1. Motivate render functions
2. Explain single `render_cell` function
`render_row` and `render_board` will be in subsequent PRs.
> :mortar_board: Tic-Tac-Toe Assignment --- Introduce render and `render_cell`

- site/assignments/tic-tac-toe/tic-tac-toe.rst
Follows #478 
Explain the `render_row` function. 
`render_board` is next.
> :mortar_board: Tic-Tac-Toe Assignment --- `render_row`

- site/assignments/tic-tac-toe/tic-tac-toe.rst
Explain the main game loop. 
1. motivate it
2. explain it
3. pseudocode
4. example runs
Also briefly talked about checking if the script was `"__main__"`. 
Sure, it's not a _big_ PR, but many of the lines are just the example output. Like 100 lines of the 151 are pseudocode or example output.
> :mortar_board: Tic-Tac-Toe Assignment --- Main game loop

- site/assignments/starbucks/starbucks.rst
- site/assignments/tic-tac-toe/tic-tac-toe.rst
- site/assignments/zombies/zombies.rst
Change big verbatim blocks (and lameo non pseudocode pseudocode) to text code blocks
It will look better
Assignments 1,2 & 3. 
Website artifact looks good :+1: 
All because on the discovery that `text` is a language option for code blocks based on @twentylemon's point in #482
> :lipstick: Assignments --- Change verbatim bits to code block

- site/assignments/starbucks/starbucks.rst
- site/assignments/tic-tac-toe/tic-tac-toe.rst
- site/assignments/zombies/zombies.rst
Add new lines between points to avoid boldfaceing text. 
Consistency
> :lipstick: Assignments --- Fix typesetting of points :microscope: 

- site/labs/lists/references.rst
1. Fix the numbering by indenting code blocks
2. Add note on the numbers list being left alone 
1. it was busted
2. Everyone tried making `nums` a dictionary
> 🐛 💄 References Lab --- Fix numbering and add note for clarity 

- site/topics/objects/interacting-objects.rst
- src/point3d.py
As discussed in #316 
Remove mention of the methods that were removed (midpoint, origin). 
YAGNI was yelled at me or something.
> :bomb: Objects III --- Remove mention of removed methods

- site/assignments/tic-tac-toe/tic-tac-toe.rst
Closes #492 
Mentioned in #478
Reorder the render function order to have board -> row -> cell -> board logic. 
1. Render board is hard
2. Wouldn't it be great if we could just say _render a row_?
3. Wouldn't it also be great if we could say _render a cell_?
More natural way of breaking a problem down.
> :lipstick: Tic-Tac-Toe Assignment --- Reorder rendering functions

- site/assignments/country-catalogue/country-catalogue.rst
Include "get item" in section title where the get item method will be described.
> :mortar_board: Country Catalogue Assignment --- add get item method to section title :microscope: 

- site/assignments/country-catalogue/country-catalogue.rst
Explain the class and mention the constructor. 
Gotta' start somewhere.
> :mortar_board: Country Catalogue Assignment --- `CountryCatalogue` intro and constructor

- site/assignments/country-catalogue/country-catalogue.rst
Explain the find and contains methods.
> :mortar_board: Country Catalogue Assignment --- `_find` and `contains` methods in `CountryCatalogue`

- site/assignments/country-catalogue/country-catalogue.rst
> :mortar_board: Country Catalogue Assignment --- `add` and `remove` methods in `CountryCatalogue`

- site/assignments/country-catalogue/country-catalogue.rst
Explain the linear search methods to find the `Country` object with the largest and smallest population densities.
> :mortar_board: Country Catalogue Assignment --- large/small linear searches

- site/assignments/country-catalogue/country-catalogue.rst
> :mortar_board: Country Catalogue Assignment --- filter method

- site/assignments/country-catalogue/country-catalogue.rst
> :mortar_board: Country Catalogue Assignment --- Mention unit tests

- site/assignments/country-catalogue/country-catalogue.rst
Explain the most populated continent method requirements.
> :mortar_board: Country Catalogue Assignment --- Most populated continent 

- site/assignments/country-catalogue/country-catalogue.rst
Mention the underscore. 
because it's "private".
> :lipstick: Country Catalogue Assignment --- Mention that the attribute should start with underscore :microscope: 

- site/assignments/country-catalogue/country-catalogue.rst
Tell them to implement the length, getitem, repr, and equals magic methods.
> :mortar_board: Country Catalogue Assignment --- Discuss required magic methods

- site/assignments/country-catalogue/country-catalogue.rst
Tell them to run the provided code
If it works, then everything probably works. 
I was originally conflicted on whether to have the students write the code to do the file IO as it was done that way in the past, but I figure (a) they can _look_ at the code to learn a little bit of the file IO, and (b) they'll do it next semester.
> :mortar_board: Country Catalogue Assignment --- Explain the provided code

- site/assignments/country-catalogue/country-catalogue.rst
Tell them what to submit
Copied from assignment 3 and then 3 -> 4. 
Should be last PR for assignment.
> :mortar_board: Country Catalogue Assignment --- What to submit

- site/topics/testing/unittest.rst
- test/test_sphere.py
Change the tests for the attributes.
Right now, checking for a point on the origin or a radius of 1 feels like it could be dumb luck default values set in a constructor. 
Made them less natural default values. 
:+1:
> :woman_technologist: :mortar_board:  Sphere tests --- change attribute tests

- site/topics/objects/interacting-objects.rst
Update the repr for the point 3d class to match code.
> :telescope:  Unittest topic --- update point repr

- site/labs/objects/objects.rst
Add a new step in the lab to write unittests for the simple classes they write. 
There are no labs on unittests, so this way they get to write some.
> :mortar_board: Objects Lab --- Add unittests to a step in the lab

- site/topics/objects/data-structures.rst
> :bug: Collections Topic (Objects IV) --- Fix typo

- site/labs/objects/objects.rst
- test/test_circle.py
This is what #528 was supposed to be. 
1. Add a link to the unittest topic
2. Add a download link to the circle tests
3. Clean up circle unittests. 
Was supposed to be for this weeks lab, but that's too late. Whatever, fixed for next year.
> :lipstick: Objects Lab --- Actually add refs, download, and clean unittests

- site/labs/objects/data-structures.rst
1. Change the assert tests to unit tests. 
2. Warn about them being tough
3. suggest having a looksie at the asn4 unit tests
We know the unit tests, and they're better.
> :mortar_board: Data Structures Lab --- assert tests -> unit tests

- .github/workflows/sphinx-build.yml
- README.md
- setup.py
Update to python 3.11
:+1:
Idk if I really wanna' merge yet. However, I do want to see if the actions work.
> :robot: Python version --- Change to 3.11

- site/assignments/country-catalogue/country-catalogue.rst
Change "cata" -> "data"
Typo 
Noticed when making asn1 for 162.
> :bug: :mortar_board: Assignment 4 --- Typo (cata -> data) :microscope: 

- site/assignments/country-catalogue/country-catalogue.rst
1. Improve example of repr format 
2. Fix it (it was comma, so make it `=`)
> :bug: :lipstick: Assignment 4 --- Improve and fix example of the repr format

- site/assignments/country-catalogue/country-catalogue.rst
- site/assignments/starbucks/starbucks.rst
- site/assignments/tic-tac-toe/tic-tac-toe.rst
- site/assignments/zombies/zombies.rst
1. Remove the weights of the assignments
2. Remove the due dates
1. Idk yet if I will make them 5, or 10, or some 5 and some 10. 
2. They are TBD
No way jose
> :mortar_board: Assignments --- Remove due dates and weights :microscope: 

- site/labs/car-rental/car-rental.rst
- site/labs/conditionals/conditionals.rst
- site/labs/debug/debug.rst
- site/labs/functions/functions.rst
- site/labs/hello-world/hello-world.rst
- site/labs/linear-search/linear-search.rst
- site/labs/lists/1d-lists.rst
- site/labs/lists/2d-lists.rst
- site/labs/lists/references.rst
- site/labs/loops/loops.rst
- site/labs/objects/data-structures.rst
- site/labs/objects/objects.rst
1. Remove mention of marks
2. Remove requirement of pre lab
3. Formatting
1. I will not be doing marks as it worked very well last year in 162
2. No marks for labs, so can't really make the pre lab required 
3. Pretty 
It is acknowledged here that, although no marks for labs in subsequent course worked amazing, it _may_ not work well here as this is first year first semester. That said:
1. Let's see. I thought it was going to be _meh_ in 162, but it was great. So maybe great here too. 
2. I am doing crazy overload, so reducing marking requirements is helpful
> :mortar_board: Labs --- Remove mention of marks

- site/topics/values-variables-types/values-variables-types.rst
Remove the 2nd use of the word "both" 
It was weird with the 2 of them
> 💄 Topic variables types --- Remove word 🔬 

- site/assignments/starbucks/starbucks.rst
Add a due date for the starbucks assignment (asn 1)
:-1: YOLO
> :mortar_board: Starbucks assignment --- Due date :microscope: 

- site/outline/outline.rst
Add dates for the first assignment and test
Would be nice to have actual dates in there.
> :mortar_board:  Outline Fall 2023 --- Set Assignment 1 and Test 1 dates :microscope: 

- site/index.rst
- site/labs/testing/testing.rst
Make new lab on testing, type hints, and docstrings 
Was not far enough along in lecture topics to hit the conditionals lab, which is currently the 3rd lab 
:+1: 
1. Some of the kattis problems I added are trivial. They wanted more though, so at least they have the skills to do these ones. 
2. More detail _could_ have been provided on the 3 "main" lab questions. For example, I didn't explain what \Delta v means. This was intentional as anything they don't know they should be able to look up, thus it is an exercise in _figuring it out_. 
3. The last question is taken from assignment 1.
> :new: :mortar_board: Lab testing --- Make new lab on testing 

- site/labs/functions/functions.rst
#582 
Add a few more Kattis problems to the end of the lab
For some weird reason, students wanted more... 
Jokes aside, this is the first year this became a problem... :thinking: 
Copied the extras added to the other new lab added in #582
> :new: :mortar_board: Lab functions --- Add more kattis problems :microscope: 

- site/assignments/starbucks/starbucks.rst
Move due date back 1 week 
One of the 4 labs will not have had a chance to do the conditionals lab before the original Oct 2nd due date. This way everyone has a chance to have more directed hands on experience.
> :mortar_board: Assignment starbucks --- New due date

- site/outline/outline.rst
#585 
Update the due date for assignment 1 on the outline. 
Consistency 
A student pointed it out to me.
> :telescope: Outline --- Update assignment 1 due date :microscope: 

- site/assignments/zombies/zombies.rst
Add a due date that is 2 weeks after asn1 is due.
> :mortar_board: Assignment zombies --- Fall 2023 due date

- site/assignments/zombies/zombies.rst
- site/outline/outline.rst
Move due date back 1 week
Not far enough along yet in the content.
> :mortar_board: Assignment zombies --- New due date :microscope: 

- site/assignments/country-catalogue/country-catalogue.rst
- site/assignments/tic-tac-toe/tic-tac-toe.rst
- site/assignments/zombies/zombies.rst
- site/outline/outline.rst
1. Set due dates for A3 and A4
2. Add % grade worth to the assignments
> :mortar_board: Assignments 3 & 4 --- Due dates :microscope: 

- site/labs/lists/references.rst
General clean up 
Consistency and proper conventions
> :bug: :mortar_board: Lab references --- Clean :microscope: 

- site/topics/objects/data-structures.rst
`Students` -> `_students`
I am referring to the attribute `_students`
> :mortar_board: :bug: Topic data structures --- Fix attribute name 🔬 

- site/index.rst
- site/outline/schedule.rst
Create a course schedule for the online asynchronous version of the course
Given that the course is asynch, they need something to give them a schedule. 
Put it under the outline section
1. I figured I would have an assignment due every 2 weeks
2. I looked at what topics would need to be known for each assignment
3. I then also took into consideration the amount of content is in each of the topics
4. I allllso took into account the topics that would _make sense_ to be grouped together
Built local, looks good. 
The specific dates of assignments and tests may change as I do not know all the details of online summer courses here
> :mortar_board: Course Schedule --- Create a schedule for the async version of the course

- site/outline/schedule.rst
1. Change asn4 due date to Sunday
2. Change final date to TBD
1. Apparently StFX Online wants the assignments due BEFORE the Monday. Sunday is before Monday. 
2. Seems like the exam is not scheduled by me
👎  YOLO
> 🎓 Schedule --- Update asn4 and exam dates 🔬 

- site/index.rst
Update the index page for summer 2024
Change all the date/times to be mentions of asyncH and reference the schedule. 
👍
> 🎓 Index --- Update for Summer 2024

- site/outline/outline.rst
Update the outline for Summer 2024
1. Remove anything about not being async
2. Add details about it being async
3. Add more details on things like how labs work as I won't be able to explain easy 
4. Details on ProctorU
:+1: 
I'm going to have to remember to revert to the regular semester outline before updating for Fall 2024
> :mortar_board: Outline --- Summer 2024

- site/assignments/country-catalogue/country-catalogue.rst
- site/assignments/starbucks/starbucks.rst
- site/assignments/tic-tac-toe/tic-tac-toe.rst
- site/assignments/zombies/zombies.rst
Update assignment due dates on assignment pages
To match the schedule
:-1: YOLO
> :mortar_board: Assignments --- Update due dates for Summer 2024 :microscope: 

- site/topics/intro/intro.rst
Remove the section talking about how there are 2 sections of the course being taught
There's 1 
:-1:
> :bomb: :mortar_board: Topic intro --- Remove reference to 2 sections :microscope: 

- site/outline/outline.rst
- site/outline/schedule.rst
Add the final exam date to the website 
So they know when it is 
:-1: 
Usually I don't post the exam date because I don't set it. I tell them to check the registrar.
> :mortar_board: Schedule --- Add final exam date :microscope: 

- site/assignments/starbucks/starbucks.rst
- site/outline/outline.rst
Set the due date for assignment 1
Nah
> :mortar_board: Assignment 1 --- Fall 2024 Due Date

- site/outline/outline.rst
> :mortar_board: Test 1 --- Fall 2024 Date :microscope: 

- site/assignments/starbucks/starbucks.rst
- site/outline/outline.rst
Move due date back 1 day 
Although not against any rule or anything, Monday is a day off, and I do not like having things due on days off. 
Nah
> 🎓 Assignment 1 --- Move Due Date

- site/assignments/zombies/zombies.rst
- site/outline/outline.rst
> :mortar_board: Assignment 2 --- Fall 2024 Due Date

- site/assignments/tic-tac-toe/tic-tac-toe.rst
- site/outline/outline.rst
Set due date to be Nov 12
1. Needs one
2. Usually I would have it on the 11th, but that's remembrance day, and there is no school that day, and I prefer not to have things due on those days
> :mortar_board: Assignment tic tac toe --- Due date fall 2024

- site/labs/lists/2d-lists.rst
change the name of variables and functions to follow Python more
> 🔭 Labs 2d lists --- Follow Python syntax 🔬 

- site/assignments/country-catalogue/country-catalogue.rst
> :mortar_board: Assignment country catalogue --- Add due date fall 2024

- site/index.rst
- site/labs/objects/data-structures.rst
- site/labs/objects/objects.rst
- site/labs/testing/unittest-objects.rst
1. Split lab 11 into 2
2. Emphasize unittests in lab 12 
3. Update last lab to include unit tests for the data structure 
Need 1 more lab, and i know people didn't finish lab 11 last week 
:+1: Built local, looks good.
> :mortar_board: Labs --- Split last labs

- site/assignments/country-catalogue/country-catalogue.rst
- site/assignments/starbucks/starbucks.rst
- site/assignments/tic-tac-toe/tic-tac-toe.rst
- site/assignments/zombies/zombies.rst
- site/index.rst
- site/outline/outline.rst
- site/outline/schedule.rst
1. Update the index page
2. Update the outline
3. Create a schedule
4. Update due dates 
:+1:
> :new: Spring 2025 --- Set up course 

- .github/workflows/sphinx-build.yml
simplify the action's install 
Remove unnecessary options 
We'll find out
> :robot: Simplify action's install :microscope: 

- site/outline/outline.rst
Set date for test 1 for Fall 2025
> :mortar_board: Test 1 --- Set date fall 2025
