- source/topic1.rst
Fix the typesetting of hello world. It was ` ``Hello, world!"`  instead of `"Hello, world!"`. 
It broke the typesetting and made a weird link back to the page. 
I've been using a lot of LaTeX lately.
> :bug: Fix typesetting  in the introduction of "Hello World"

- source/index.rst
- source/topic1.rst
Add a link to the twitch channel for "Office Hours". 
So they can find it easy. 
This will now be closer to the index page for CS 102.
> :new: :mortar_board: Add link to twitch channel 

- source/index.rst
Add a link to the github page for the course. 
Students can easily access it from the page itself. Hopefully it will make it easier to participate in the content creating. 
Right near the top, under the description.
> :mortar_board: add GitHub link

- source/topic12.rst
Related to #12 
Change `airportCode` -> `airport_code` and `airportlist` -> `airport_list`. 
Consistency & convention.
> :telescope: :lipstick: Topic12 Change airport variable names to follow convention

- source/conf.py
Fixes the math rendering issue noted in #50 
Change the math `sphinx.ext.imgmath` -> `sphinx.ext.mathjax`, like how it is for cs102. 
Wasn't working correctly because I think something with LaTeX
Copy from cs102's conf.py file
~I _will_ verify after action~ 
Yep --- works.
> :lipstick::bug: Topic3 (kinda) Change the math extension

- source/lab2.rst
Add a link the explination of `return` in the course content. Also, I added whitespace too. 
It will ideally help them with independent learning (at least, they will hopefully click the link) 
Trying with `:doc:`, but I don't actually know if I can do it the way I did. 
~I'll check the build to see if it works.~
It didn't work, I changed it to just a link and it works. 
If it doesn't work with `:doc:`, it will with this: `What return? <http://modsurski.com/csci161/topic3.html#function-values>`_
> :mortar_board: Lab2 Add link to course content on `return`

- source/topic3.rst
1. Add spaces between params
2. add spaces to match operator conventions (apparently in Python they recommend no space for things of higher priority --- I never knew this)
3. Changed single quote to double quote. Not needed, but idk, will match Java for next semester better. 
4. Assign the function's returned value to a variable to help emphasize that it's being evaluated to a value
Mostly for conventions.
> :mortar_board::lipstick: Topic3 Clean up `do_stuff` example

- source/index.rst
1. Remove the excess **'GO HERE'** for YouTube.
~2. Bold face the names for more of a pop~
2. Make prof names subsection titles. 
Looked like a mess, and Jean-Alexis' name felt lost in the points.
> :lipstick: Clean up prof part of index page

- source/index.rst
Quick change to #58 
Change the prof names from being subsections to just bold faced. 
1. The subsection strategy ended up making the font too big
2. The bold face was used everywhere else on the page.
> :lipstick::telescope: Change names to bold from subsections

- source/asn1.rst
Remove the instructions for unzipping the `.ipynb` file since it's no longer downloaded as a compressed folder. Remove the image of the unzipping too. 
Also added words to the details for saving to Colab. 
I guess it no longer was compressed. I must've changed this last year but accidentally left the details on unzipping in. 
The reason it was compressed before was because chrome and other browsers warned that there was scripts in there and a security problem. The compressed folder bypassed the issue, but I guess it's no longer needed? Whatever.
> :bomb: Asn1 Remove details of unzipping file

- source/lab1.rst
- source/lab10.rst
- source/lab11.rst
- source/lab12.rst
- source/lab2.rst
- source/lab3.rst
- source/lab4.rst
- source/lab5.rst
- source/lab6.rst
- source/lab7.rst
- source/lab8.rst
- source/lab9.rst
Remove the details at the end of each lab explaining that the online section must submit their lab via Moodle. 
There is no online section this year, and these instructions just confuse the students. 
End of all lab files. It was a WARNING.
I was gonna' just comment it out just in case it came back in the future, but (a) I don't think online sections will be back for a while, (b) it's easy to just add the warning back in, and (c) I was too lazy if commenting out the warning would actually work since  the `..` for comments is similar to `.. warning::` for warning, so, idk. Easier to just delete.
> :bomb: Labs Remove 'online section' instructions

- source/index.rst
Add the day, time, and place for the MSCS tutorial nights. 
Students can go there for peer help. 
Defo should have done this earlier.
> :new: Add tutorial nights to index page

- source/lab4.rst
- source/topic5b.rst
Remove "... because they hate young people" from the car rental example. 
Feels unnecessary. 
I was thinking of changing it to something to insult boomers, but decided against it. Something like "boomers can't be ageist I guess".
> :bomb: Remove comment about hating young people in car rental eg

- source/topic5b.rst
Remove the second 'based' in the comment for the `total_kms` function comment. 
It was there 2x for some reason.
> :bug: Topic5b Remove extra 'based' in comment

- source/lab6.rst
- Add a space between the parameters.
- Rename `char` -> `character` and `string` to `phrase` params for the functions.
- Spacing for consistency. 
- Renaming the params since `char` and `string` are keywords in other languages, so this just makes things more different. 
Lab 6, questions 1 -- 4. 
`char` and `string` are fine in python, but this helps make things more distinct. Further, sometimes new students get mixed up with the variable/param names and thinking that, because it's a string, it **has** to be called string, which is not correct.
> :lipstick: Rename params and add space

- source/topic11.rst
Closes #94 
Unindent the function call in the one example. 
Because currently the call is in the function, not outside the function. What makes it worse is, this is an example of debugging and, sure this is also a bug, it's not the point of the example. 
`count_numbers_up_to`
> :bug: :lipstick: Unindent function call

- source/topic13.rst
Closes #97
Fix the spelling of "Spyder".
It is misspelled as "Sypder".
Topic 13, The second "Warning" block (line 138).
> :bug: Spyder spelled wrong

- source/lab11.rst
Closes #103 
Fix the links to the `toSearchA.txt` and `toSearchB.txt` files. 
They were broken --- they were pointing to the old uni website. 
Switched to `:download:` so it's more general.
> :bug: Lab11 Fix broken links to text files

- .github/workflows/sphinx-build.yml
Change build source from `source` to `site` 
It was named that in the restructure. Also, github wouldn't let me change it locally? idk. whatever. 
This is because my access token did not include workflows in its scope. I'm looking for a quick workaround for this time.
> :robot: Update workflow following restructuring

- .github/dependabot.yml
As suggested by @twentylemon in #115. 
Add dependabot to repo.
Keep things up to date. Further, it would have already solved one of my early issues. 
Stole from [duckbot](https://github.com/duck-dynasty/duckbot/blob/main/.github/dependabot.yml).
> 🤖:memo: Add Dependabot to repo

- site/topics/functions/functions.rst
Fix the docstring details --- change the first `:` to an `@`.
~I guess the `@` is more correct? At least that's what pycharm says, so I trust that.~
PyCharm seems to suggest the `@`, but I can't find details on that actually being standard or anything. Either way, I'll go with what PyCharm says as it likely has more method to the madness than I do.
> 🐛 Functions Comments emphasize `:`

- site/topics/functions/functions.rst
Correct the `square_of_sums` function examples within the functions topic. I also simplified the activity where they do mental math to make the mental math easier. 
I originally was treating it as if it was `sum_of_squares`.
> :bug: Functions Correct `square_of_sum` Function Examples

- site/topics/booleans/booleans.rst
Change to #167 
Change the header row in the truth table by reducing the use of `verbatim`. 
Currently, with the full use of `verbatim`. the boldface emphasis on the header is hard to see.
> :lipstick: BoOleans Topic Change Truth Table Header

- site/conf.py
Change year to 2022. 
Because it's 2022. 
Only changing it to 2022 because of the significant changes taking place.
> :bug: © 2021 -> 2022 🔬 

- .github/ISSUE_TEMPLATE.md
Update the issue template to get rid of the new line. 
The extra newline after the heading and the text is annoying. CS102 already has it without the newline. 
Will have a separate PR for the PR template.
> 📝 Update Issue Template 🔬 

- site/topics/fileIO/fileIO.rst
Remove the `+` 
It's Unnecessary 
`+` were/are used to indicate that it is a particularly difficult activity, but this one isn't really.
> 🐛 FileIO remove `+` in activity name 🔬 🔬 

- src/circle.py
- test/test_circle.py
Adds to #278 
Include `__eq__`  and `__repr__`.
These methods will **not** included in the Topic focusing on the `Circle` class, but will be added to the Topic covering the `Point` class when those magic methods are used --- something like "could've totally added these to our Circle class too!"
:+1:
> 🆕 Circle magic methods

- site/labs/references/references.rst
Remove the duplicate section title for Kattis problems.
> :bug: Lab Refs and Lists remove extra section title 🔬 

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
Undoes #231 
Add the new line back to the template files. 
It was getting annoying to discard the changes to the md files every time I ran format. mdformat insists on the new line, and I looked into adding an exception to that rule for these files, but whatever, it's easier to make it shutup this way. 
Also, if the good people of _mdformat_ believe the new line is important, I will yield to them.
> 📝 Add new lines back to template 🔬 

- site/index.rst
Was removed in #286, but came back somehow 🤷 
Remove the link to the debug lab from the index page.
> 💣 Debug Lab remove link/ref from index

- site/index.rst
- site/topics/objects/data-structures.rst
- site/topics/objects/interacting-objects.rst
As discussed with @twentylemon  in #315 
1. Make a new objects topic to come after the `Sphere` implementation
2. Introduce the topic
3. Move the Data structures topic back
1. The flow of the content will be improved
The existing PRs (#315, #316, #317, #318) will be updated by moving the content to this topic after this PR is merged.
> :new: Objects Topic Shuffle make new topic and move other topics around

- src/sphere_original.py
- test/test_sphere_original.py
Made a class for the original `Sphere` class
This version will be the one we introduce the `Sphere` with before refactoring to have a `Point3D` class. I wanted a working version in the repo with unittests for completeness. 
Yes, but the simple `assert` tests are defo lacking. That said, I am not worried as this will be pointed out in the topic, saying something like "uhh, feels incomplete, but it's getting mangled..."
> 🎓 Original Sphere Class make a class containing the `Sphere` before `Point3D` 

- site/outline/outline.rst
Explain _assignment recoupment_. 
This is something I did back in like 2016/2017. The idea is, students can take their returned assignments, correct mistakes, and recoup 50% of the lost marks. 
Eg. 
- A student gets 80/100
- They correctly fix things that account for 15 of the 20 lost marks
- They get +7.5 on the assignment for a total of 87.5/100. 
Motivation:
(a) Students are expected to make mistakes and are an essential part of learning
(b) Marks are not intended to be a reward/penalty; marks are for feedback
(c) We want students to actually look at their assignment feedback and use it as a learning opportunity 
(d) Marks tend to be very bimodal, and struggling students stand to benefit the most from this idea
(e) Students that actually care are the ones that will do this
(f) The …
> 🆕 Syllabus --- Assignment Recoupment

- site/outline/outline.rst
Note in the syllabus that, if the midterm is not written, the final exam will include the midterm's portion of the final mark. This would mean their final is worth 50%. 
- The university/department has no mechanism to properly administer makeup midterms
- Each makeup midterm is the responsibility of the professor to schedule and proctor
- With the general increase in accommodations needed, this eliminates the need to have make up midterms.  
- With the increase that will come in COVID accommodations, this will further eliminate any headache
Having done this multiple times in the past at UWO, it ends up working out pretty well. Some students opt to just not write as they have many other midterms and they are happy to have the reweighting anyways. There may be a small number of students …
> 🎓 Syllabus --- Missed midterm and reweight final

- site/topics/intro/intro.rst
Change waring -> warning
Because it's a warning, and not really about waring.
> :bug: Intro --- Change waring -> warNing

- site/outline/outline.rst
Add the course email address to the syllabus. 
So the students know it exists.
> :new: Syllabus --- Add course email to syllabus

- site/labs/hello-world/hello-world.rst
The pre-lab exercises talk about "the interpreter", and since this is the first actual thing they have to do on their own, I mention that they are using colab, and ignore "the interpreter".
Could totally cause confusion.
> :new: Lab1 --- Mention Colab instead of Interpreter 

- site/index.rst
Add the math, stats, and CS student society tutorial night to the index pafe. 
It's free extra help. 
Right on the home page. 
I assume there is no specified end time?
> :mortar_board: Index --- Add Math, Stats, and CS Society tutorial time

- site/topics/booleans/booleans.rst
Remove the `**` from the code like text examples. 
It wasn't rendering the way it was intended. Looks like rst is not happy with bold code like text.
> :bug: Booleans Topic --- Remove bold face from code like texet :microscope: 

- site/index.rst
Move the Booleans topic to be before the testing topic. 
We make use of the boolean operators in the testing topic, so it would be nice to talk about them before they need to use them. 
Just changed the order of the topics in the index. 
Urgent because these topics are happening today.
> :lipstick: Index --- Move Booleans topic before Testing topic :microscope:

- site/topics/testing/testing.rst
- src/functions_topic.py
Change the one assert test with floating point result to use the absolute difference test
Although the particular test is fine the way it is, since I just went on about avoiding comparing floats directly with `==`, and I do not compare with `==` in the subsequent test with floats, it only makes sense for consistency. 
:+1:
> :telescope:  Testing Topic --- Change C -> F floating point test 

- site/labs/conditionals/conditionals.rst
- site/labs/linear-search/linear-search.rst
- site/labs/lists/1d-lists.rst
- site/labs/lists/2d-lists.rst
- site/labs/lists/references.rst
- site/labs/loops/loops.rst
- site/labs/objects/data-structures.rst
Add a requirement to do assertion tests for the pre-lab exercises from the conditionals lab forward (where applicable). 
1. Testing is good
2. Seems like students are cheating on the pre-lab exercises a lot by finding solutions online. Checking if they did the tests will be easy, and if they do cheat, but at least did the tests, then we can concede that they spent time thinking about solutions. 
All labs where applicable from the 3rd lab forward. 3rd lab forward since that will be roughly where they see the assertion tests. 
When going through the pre-lab exercises, some were pretty rough. May need to adjust going forward --- we'll see.
> :new: Labs --- Include testing requirement for pre-lab exercises

- site/labs/conditionals/conditionals.rst
Remove questions 2 & 3.
They're dumb. It has them use input, which I do not like in general. Further, it always throws students off because they are so simple and they have just done it more-or-less already when doing Q1. 
Literally doing this in lab right now.
> 💣 Conditionals Lab --- Remove Dumb Questions

- site/labs/objects/data-structures.rst
Fix the numbering in the lab exercises. 
It's busted. 
Added a `.` after the `#`
> :bug: Data Structures Lab --- Fix numbering :microscope: 

- site/labs/conditionals/conditionals.rst
Remove Q2 from the pre-lab exercises. 
1. It's mean at this point
2. Chances are we wont have hit `%`, which it will need
3. It doesn't require any conditionals (though, it should call Q1, which does), which is the point of the lab. 
The only value the question has is the fact that it should use the function from Q1, but the challenge doesn't justify it; pre-lab are supposed to be easy and the students are struggling with it. 
There is a similar argument to be made about Q10, and how it doesn't use conditionals, but it's simple enough, and it will help them remember triangle stuff which is needed for Q11.
> :bomb: Conditionals Lab --- Remove Q2 from prelab

- site/labs/loops/loops.rst
Fix the math range typesetting. 
It was wrong, and made it confusing since the two dashes looked like it was a range from 0 to a negative number. 
Just made the range `--` not in math mode.
> :bug: Lab 5 --- Fix math range typesetting :microscope: 

- site/labs/linear-search/linear-search.rst
Remove the prelab question 4
It's a bad question. It makes no sense. it's confusing. There are problems. Does the `find` method have an optional third param? (it doesn't) We add the third param to keep looking for letters, even though the function `count_letters` is doing that already? wut?
Not this year, but will need to look at the "not required" questions from the pre-lab to add some back in to be required.
> :bomb: Linear Search Lab --- Remove prelab q4 

- site/labs/lists/2d-lists.rst
changed the before kattis question numbers so they are in correct order by indenting images. 
idk, felt like it lol
lab 8-2D lists
on here, idk if i did it right
> :bug: 2D List Lab 8 --- Indent images to fix numbering

- site/topics/objects/interacting-objects.rst
Just like #500 
Add `import math` before each example of the class code. 
It had confused them before, and for the sake of consistency, here too.
> :telescope:  Objects III --- Add more imports to math

- site/topics/testing/unittest.rst
- test/test_sphere.py
Change the repr test for the `Sphere` class in the topic notes
It's wrong. I believe it _was_ this way before, but at some point got updated. 
There is a # to ref, but I didn't find it in 2s, so I give up. Too inconsequential to dig deeper.
> :bug: :telescope: Unittest topic --- Update repr test

- site/assignments/tic-tac-toe/tic-tac-toe.rst
Change where the `"X"` is applied to in the example apply move function description. 
It's wrong; I have it backwards. Based on the  (x, y) coordinates, the `"X"` should be not where it was.
> :bug: Tic-Tac-Toe Assignment --- Fix example for `apply_move` :microscope: 

- site/assignments/country-catalogue/country-catalogue.rst
Add missing backticks around the `population` attribute.
> :bug: Country Catalogue Assignment --- Add missing backticks :microscope: 

- site/labs/objects/objects.rst
1. Add link to unittest topic
2. Add download link to circle unittests
3. Remove the use of `setUp` in circle unit tests
4. remove dumb tests
1. Helpful
2. Helpful (were doing it already, so why not add link)
3. It threw them off
4. they were dumb
:+1:
> :lipstick: Objects Lab --- Reference unit test stuff & clean circle tests

- site/topics/sorting/sorting.rst
1. Switch out the sorting algo names in the activities (it said selection when it was insertion, and insertion when it was selection)
2. Add extra backticks to properly do the typesetting.
> :bug: Sorting Topic --- Fix algo names in activity and typesetting

- site/_static/css/custom.css
- site/_static/js/on_load.js
- site/conf.py
:lipstick: 
Following #195
Update the custom.css file with new admonition classes and colors.
Create a JS file to give a "mac" header to code-block and a clipboard button to copy the code.
Improve the color of the activities and other admonitions.
Everywhere.
New CSS and JS files and modification of conf.py.
How to use the new admonition classes:
- Activity:
```
.. admonition:: Activity
:class: activity
```
- Example:
```
.. admonition:: Example
:class: example
```
>  :lipstick:  Update css and create other admonition classes

- site/outline/outline.rst
Found by @twentylemon in another course 
Change the course code from 162 -> 161
This is for 161, not 162
Under the email part of the outline 
:-1: 
Caused by a lazy copy/paste from CSCI 162.
> :bug: Outline --- Fix course code to say 161 :microscope: 

- site/labs/testing/testing.rst
Remove Q7 from pre-lab
Takes away from the point of the lab
> 💣 Remove Q7 from Pre-Lab

- site/labs/testing/testing.rst
typehint -> type hint 
It's weird as one word.
> 🐛 Labs testing --- Add space to "type hint"

- site/topics/if-else/if-else.rst
- src/if_else_topic.py
Use different variable in the division calculation of the `smush` function 
I made a point about using 2 vars in the function (`return_value` and `a_number`) instead of 1 as I felt it made the code clearer despite it having no functional difference. One keen student then said, "would it also not make sense to use the `a_number` in the division calculation since it's the `a_number` that is divided by 2", which I totally agree with. 
:+1: 
1. It's a small chance, but I'm for it as the student is totally right and I think it's cool that someone noticed something like this
2. I have yet to change csci161 to use the `literal-include`, so I had to chance the code in 2 spots (src and in the topic).
> :lipstick: :technologist:  Topic if else --- Use `a_number` in calculations :microscope: 

- site/outline/outline.rst
Set the date for test 2
Originally planned for end of oct, but they wanted the test after reading week, so whatever, it's the first wed after reading week. 
The joke is, if you make the test before reading week everyone complains that you should've given them reading week to study for the test. If you make the test after reading week, they complain that you ruined their reading week and that they got rusty from not having class during reading week.
> :mortar_board: Outline --- Test 2 date :microscope: 

- site/topics/searching/searching.rst
1. Add a space between word and `if` 
2. Add type hints to Python code
1. So it renders correctly
2. To make the Python syntax more like the strongly typed languages
YOLO
> :bug: :lipstick: Topic searching --- Fix `if` and add type hints :microscope: 

- site/topics/testing/unittest.rst
Swap the `expecteds` and `cases` variable names
They were reversed 
YOLO
> :bug: :mortar_board:  Topic unittest --- Fix general subtest example :microscope: 

- site/outline/outline.rst
- site/outline/schedule.rst
Reduce the number of tests to 2 from 3. One midterm and a final. 
Apparently, because it's remote, they need to pay for a proctor themselves out of their pockets at a price of $40/test, which is lameo. 
Reduce number of tests. Move test 1 one week, and update the grade breakdown. 
:-1:
> :mortar_board: Tests --- Only have 2 tests :microscope: 

- site/outline/outline.rst
- site/outline/schedule.rst
Move the midterm back 1 week, again. 
More content would have to be covered (lists), and based on the schedule, this seems to be the best place to put the test such that they know enough about lists. 
:-1: 
When combining the two midterms, some of the content from the 2nd test was cut since not enough content will be covered in the lectures/labs/assignments. That's OK though as I don't want the test to be too long anyways.
> :mortar_board: Schedule --- Move midterm back 1 week :microscope: 

- test/test_course.py
added tests for course.contains() and course.remove() where there are zero students in the course
> Update test_course.py to add tests for zero students
